name: Poiji Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build and Test with Maven
        run: mvn clean -B package --file pom.xml -P coverage
      - name: Codecov GitHub Action
        uses: codecov/codecov-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
